version: '3'
services:
  basedatos:
    image: mysql:8.0
    container_name: basededatos-prueba
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: prueba
      MYSQL_USER: prueba
      MYSQL_PASSWORD: 123456
    volumes:
      - ./database:/var/lib/mysql
